# Generated by Django 5.0 on 2023-12-10 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalchart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='year_in_school',
            new_name='grade_in_school',
        ),
    ]
