# Generated by Django 5.0 on 2023-12-11 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalchart', '0002_rename_year_in_school_student_grade_in_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='goalchart.student'),
        ),
    ]
