# Generated by Django 5.0 on 2023-12-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalchart', '0004_remove_rating_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='goal_rating',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
