# Generated by Django 5.0 on 2023-12-11 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalchart', '0005_goals_goal_rating_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='goalchart.schedule'),
        ),
    ]
