# Generated by Django 5.0 on 2023-12-17 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalchart', '0007_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goals',
            name='student',
        ),
        migrations.AddField(
            model_name='goals',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='goalchart.schedule'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='goals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_ratings', to='goalchart.goals'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='goalchart.student'),
        ),
    ]
