# Generated by Django 5.0 on 2023-12-18 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalchart', '0009_goals_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goals',
            new_name='Goal',
        ),
    ]
