# Generated by Django 5.0 on 2024-01-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalchart', '0012_remove_schedule_day_of_the_week_schedule_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={},
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='activity',
            new_name='activity_1',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='period_number',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='picture',
        ),
        migrations.AddField(
            model_name='schedule',
            name='activity_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='activity_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='activity_4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='activity_5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='activity_6',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='activity_7',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day_of_the_week',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], default='MON', max_length=3),
        ),
        migrations.AddField(
            model_name='schedule',
            name='picture_1',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='picture_2',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='picture_3',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='picture_4',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='picture_5',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='picture_6',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='picture_7',
            field=models.URLField(null=True),
        ),
    ]
