# Generated by Django 5.0 on 2024-01-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalchart', '0013_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day_of_the_week',
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
