# Generated by Django 5.0 on 2024-01-04 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalchart', '0015_alter_schedule_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200, null=True)),
                ('activity_description', models.TextField()),
                ('activity_picture_url', models.URLField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='picture_1',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='picture_2',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='picture_3',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='picture_4',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='picture_5',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='picture_6',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='picture_7',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='activity_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_activity_1', to='goalchart.activity'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='activity_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_activity_2', to='goalchart.activity'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='activity_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_activity_3', to='goalchart.activity'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='activity_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_activity_4', to='goalchart.activity'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='activity_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_activity_5', to='goalchart.activity'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='activity_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_activity_6', to='goalchart.activity'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='activity_7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_activity_7', to='goalchart.activity'),
        ),
    ]
