# Generated by Django 5.0 on 2024-01-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalchart', '0016_activity_remove_schedule_picture_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_description',
            field=models.TextField(null=True),
        ),
    ]
